services:
  db:
    image: postgres:14-alpine
    container_name: pgdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bn_db
    ports:
      - "5432:5432"

volumes:
  postgres_data: